SELECT 
    YEAR(E1.DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - E1.SIZE_OF_COLONY AS YEAR_DEV,
    E1.ID
FROM ECOLI_DATA E1
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(E1.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;