select A.BOOK_ID , B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE , "%Y-%m-%d") AS PUBLISHED_DATE
from BOOK A
join AUTHOR B
on A.AUTHOR_ID = B.AUTHOR_ID
where A.CATEGORY = "경제"
order by PUBLISHED_DATE ASC;
